#define COLOR_VERMELHO  "\x1b[31m"
#define COLOR_VERDE     "\x1b[32m"
#define COLOR_AMARELO   "\x1b[33m"
#define COLOR_AZUL      "\x1b[34m"
#define COLOR_MAGENTA   "\x1b[35m"
#define COLOR_CIANO     "\x1b[36m"
#define COLOR_RESET     "\x1b[0m"